### ISSUE TITLE
How do I use --eval_only?

### ISSUE THREAD

**Issue by alvin-leong** [clovaai/FocusSeq2Seq#1]
I have run through the code following the instructions and trained a QG model. My best checkpoint was 7.

So this next time round, I just want to load the saved checkpoint and look at the outputs from the val set. 

Here are my configs: 

`!python train.py --task=QG --model=NQG --load_glove=True --feature_rich --data=squad \
    --load --load_ckpt=7 --eval_only`

I keep on getting this error:

> Traceback (most recent call last):
> File "train.py", line 136, in <module>
>   n_iter = len(train_loader)
>TypeError: object of type 'NoneType' has no len()

So if I understand it correctly, with eval_only, I should by-pass loading the training and validation sets and just test it.

However, there is no actual code in train.py to look at "eval_only" as far as I can see. It will always assume I am going through the whole training.

**Comment by j-min** [comment]
I just updated the evaluation commands [here](https://github.com/clovaai/FocusSeq2Seq/commit/015f4478c8907547682c0637254e5080b63f7357). Please check.
