### ISSUE TITLE
'chmod' is not recognized as an internal or external command !!!

### ISSUE THREAD

**Issue by riturajkunwar** [clovaai/FocusSeq2Seq#3]
On executing the command:                python train.py --task=QG --model=NQG --load_glove=True --feature_rich --data=squad --rnn=GRU --dec_hidden_size=512 --dropout=0.5 --batch_size=64 --eval_batch_size=64 --use_focus=True --n_mixture=3 --decoding=greedy

I get following error:

'chmod' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from utils.tensor_utils import repeat
  File "C:\Users\Emergent Tech HP\my_projects\NQG_python3.6\FocusSeq2Seq\utils\__init__.py", line 1, in <module>
    from .rouge import *
  File "C:\Users\Emergent Tech HP\my_projects\NQG_python3.6\FocusSeq2Seq\utils\rouge\__init__.py", line 1, in <module>
    from .perl_rouge import *
  File "C:\Users\Emergent Tech HP\my_projects\NQG_python3.6\FocusSeq2Seq\utils\rouge\perl_rouge.py", line 15, in <module>
    _ = Rouge155(rouge_dir, log_level=0)
TypeError: __init__() got an unexpected keyword argument 'log_level'

Am I getting this error because I am using windows machine ??

**Comment by j-min** [comment]
Yes chmod is not a Windows command.

Btw, the error message below seems a separate issue.
`Rouge155` class from pip version pyrouge does not have `log_level` keyword argument as [here](https://github.com/bheinzerling/pyrouge/blob/master/pyrouge/Rouge155.py#L74).
I just updated the pip install command in [a new commit](https://github.com/clovaai/FocusSeq2Seq/commit/7c2265091e8a914c87133f7a26e84900ac7325b8).
You can `pip install git+git://github.com/bheinzerling/pyrouge`

**Comment by j-min** [comment]
If you just want to run QG model, you can comment out [here](https://github.com/clovaai/FocusSeq2Seq/blob/master/utils/__init__.py#L1).

**Comment by riturajkunwar** [comment]
Thanks for your help .... Its hard to make it work on windows machine.... So moved on to Ubuntu machine !!

**Comment by Geoffrey-lab** [comment]
You could also try the cloud-based Jupyter Notebook environment,  like Google Colab that allows you to execute Unix-like commands, including 'chmod,' within code cells by prefixing them with '!' (ex: !chmod).
