### ISSUE TITLE
AssertionError in  Ubuntu 14.04.5

### ISSUE THREAD

**Issue by alznn** [clovaai/FocusSeq2Seq#5]
Hi 
I used conda to install all lib mention in requirement.txt
however, when I try
`python train.py --task=QG --model=NQG --load_glove=True --feature_rich --data=squad --rnn=GRU --dec_hidden_size=512 --dropout=0.5 --batch_size=64 --eval_batch_size=64 --use_focus=True --n_mixture=3 --decoding=greedy
` 

I got this result：
`  
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from utils.tensor_utils import repeat
  File "/home/alznn/focusseq2seq/FocusSeq2Seq/utils/__init__.py", line 1, in <module>
    from .rouge import *
  File "/home/alznn/focusseq2seq/FocusSeq2Seq/utils/rouge/__init__.py", line 1, in <module>
    from .perl_rouge import *
  File "/home/alznn/focusseq2seq/FocusSeq2Seq/utils/rouge/perl_rouge.py", line 13, in <module>
    assert os.path.exists(rouge_path)
AssertionError
`
Do anyone have any idea about this error?

**Comment by j-min** [comment]
Have you installed the ROUGE-1.5.5 below the python lib requirements?
If you're not interested in summarization, you can simply comment out importing `utils/rouge` [here](https://github.com/clovaai/FocusSeq2Seq/blob/master/utils/__init__.py#L1).

**Comment by alznn** [comment]
> 
> 
> Have you installed the ROUGE-1.5.5 below the python lib requirements?
> If you're not interested in summarization, you can simply comment out importing `utils/rouge` [here](https://github.com/clovaai/FocusSeq2Seq/blob/master/utils/__init__.py#L1).

Yeah!!!
it works~~
Thanks a lot!!!!
